method:
  name: gcsc
  number_of_outputs: 10
  loss: cross_entropy
  randaugment: true

augmentation:
  name: RandAugment
  number_of_operations: 2
  magnitude: 9

training:
  initialize_from: random
  maximum_epochs: 100

checkpoint:
  filename: gcsc_best.pt

evaluation:
  primary_unknownness_score: mls
